apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-in-k8s.fullname" . }}
  labels:
    {{- include "k8s-in-k8s.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-in-k8s.selectorLabels" . | nindent 4 }}
